const signup: any = {
  en: {
    // signup page
    signUpTitle: 'Create my account',
    nameTitle: 'Name',
    familyNameTitle: 'Family Name',
    emailTitle: 'Email',
    companyName: 'Company Name',
    role: 'Your Role',
    numberOfPeople: 'Number of people on your team',
    passwordTitle: 'Password',
    passwordVerifyTitle: 'Password Verify',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password ?',
    acceptCgus: 'By registering you accept',
    acceptCgusLinkTitle: 'our Terms & Conditions',
    acceptCgusLink: '',
    alreadyAccount: 'Already have an account ?',
    signUpButton: 'Create my account',
    login: 'Connect',
    welcomeSignup: 'Welcome {{name}}',
    welcomeQuestion: 'We have a few questions for you',
    why: 'What do you want to use getFluence for ?',
    weReady: 'We are all set, what do you want to start with ?',
    welcomeGetFluence: 'Hurray ! Welcome to getFluence',
    previousStep: 'Go back',
    nextStep: 'Next Step',
    companyPlaceHolder: 'Pick or create a company',
    jobSelect: '- Sélect -',
    cLevelJob: 'C-level',
    financeJob: 'Finance',
    productJob: 'Product',
    salesJob: 'Sales',
    importSaas: 'Import my Saas',
    newSearch: 'Start a new search',
    discoverDashboard: 'Discover my dashboard',
    dataSecure: 'Your data is 100% secured and only used to get your Saas subscription data',
    // validation errors
    wrongEmailFormat: 'Wrong email format',
    wrongPasswordFormat: 'Wrong password format, should contain at least 8 characters',
    wrongFirstNameFormat: 'Wrong first name format',
    wrongLastNameFormat: 'Wrong last name format',
    passwordsMismatch: 'Passwords mismatch',
    wrongCompanyNameFormat: 'Wrong company format',
    // number of peoples choices
    justme: 'Just me',
    // choices options
    findBestTools: 'Find the best Saas',
    saveMoney: 'Get great deals on Saas',
    manageMyStack: 'Manage my Saas',
    allTheAbove: 'All of the above',
    // api errors
    errorWrongPassword: 'Wrong password',
    errorUnknownUser: 'Unknown user',
    errorNotAllowed: 'Unauthorized',
    errorAlreadyExistingUser: 'Already existing user',
    errorCannotSignup: 'Error cannot signup',
    errorSignupMoreThanOneUser: "You can't signup more than 1 user by company for the moment",
    errorSignupMoreNotSubscribedCompany: "We are in Beta, we didn't subscribe your company go to https:// and fill in the survey to be in the wait list",
  },
  fr: {
    // signup page
    signUpTitle: 'Créez votre compte',
    nameTitle: 'Prénom',
    familyNameTitle: 'Nom',
    emailTitle: 'Email',
    companyName: "Nom d'Entreprise",
    role: 'Votre Rôle',
    numberOfPeople: 'Nombre de collaborateurs',
    passwordTitle: 'Mot de passe',
    passwordVerifyTitle: 'Vérification mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    acceptCgus: 'En vous inscrivant vous acceptez',
    acceptCgusLinkTitle: 'nos CGUs',
    acceptCgusLink: '',
    alreadyAccount: 'Vous avez déjà un compte ?',
    signUpButton: 'Créez mon compte',
    login: 'Connectez-vous',
    welcomeSignup: 'Bienvenue {{name}}',
    welcomeQuestion: 'Nous avons quelques questions à vous poser',
    why: 'Dans quel but souhaitez-vous utiliser GetFluence ?',
    weReady: 'Tout est prêt, par quoi voulez-vous commencer ?',
    welcomeGetFluence: 'Hourra ! Bienvenue à GetFluence {{name}}',
    previousStep: 'Retour',
    nextStep: 'Suivant',
    companyPlaceHolder: 'Sélectionnez ou créez une entreprise',
    jobSelect: '- Sélectionnez -',
    cLevelJob: 'Direction',
    financeJob: 'Finance',
    productJob: 'Produit',
    salesJob: 'Vente',
    importSaas: 'Importer mes Saas',
    newSearch: 'Commencer une nouvelle recherche',
    discoverDashboard: 'Découvrir mon dashboard',
    dataSecure: 'Vos données vous appartiennent et sont 100% sécurisées',
    // validation errors
    wrongEmailFormat: "Merci d'utiliser une adresse mail valide",
    wrongPasswordFormat: 'Mot de passe au mauvais format, il doit contenir au moins 8 caractères',
    wrongFirstNameFormat: 'Mauvais format de prénom',
    wrongLastNameFormat: 'Mauvais format de nom',
    passwordsMismatch: 'Mots de passe ne correspondent pas',
    wrongCompanyNameFormat: 'Mauvais format entreprise',
    // number of peoples choices
    justme: 'Moi',
    // choices options
    findBestTools: 'Découvrir les meilleurs Saas',
    saveMoney: 'Faire des économies',
    manageMyStack: 'Gérer mes logiciels',
    allTheAbove: 'Tout ce qui précède',
    // api errors
    errorWrongPassword: 'Mauvais mot de passe',
    errorUnknownUser: 'Utilisateur inconnu',
    errorNotAllowed: 'Non autorisé',
    errorAlreadyExistingUser: 'Ultilisateur déjà enregistré',
    errorCannotSignup: "Erreur impossible de s'enregistrer",
    errorSignupMoreThanOneUser: "Vous ne pouvez pour l'instant pas inscrire plus de 1 utilisateur par entreprise",
    errorSignupMoreNotSubscribedCompany: "Nous sommes en Beta, nous n'avons pas inscrit votre entreprise, rendez-vous sur https:// et complétez le formulaire pour être dans la liste d'attente",
  },
};

export default signup;
